# ---------------------------------------------------------------------------
# Type: tool
# Purpose: "Installs the watchdog so it starts at login and runs from now on,
#           and is the one place the interval is written down."
# Depends on: [scripts/watchdog-loop.ps1, scripts/watchdog.ps1]
# Depended on by: [docs/status-ledger.md]
# ---------------------------------------------------------------------------
#
# Run this to install the watchdog, and run it again to change how often it
# checks. It replaces what is there rather than adding to it, so running it twice
# is the same as running it once.
#
#   powershell -ExecutionPolicy Bypass -File scripts\watchdog-install.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\watchdog-install.ps1 -CheckEveryMinutes 15
#
# **This does not use Task Scheduler, and that was not the first choice.** A
# scheduled task was written, registered, and did nothing: it reports success and
# the process never starts, last result 1, and a task whose entire action is
# `cmd.exe /c echo` into a file fails the same way. Diagnosing that needs
# administrator rights this account does not have. The HKCU Run key does work
# here, demonstrably, because it is how Docker Desktop starts. See
# scripts/watchdog-loop.ps1.
#
# To see what it has been doing:
#
#   Get-Content "C:\Users\Randy\AppData\Local\vsv-watchdog\watchdog.log" -Tail 40
#
# To take it away:
#
#   Remove-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" -Name "VSV cellar watchdog"

[CmdletBinding()]
param(
  # **The interval, and the only number here worth thinking about.**
  #
  # The check costs about half a second when everything is fine, so this is not a
  # question about load. It is how long the app stays offline before it heals
  # itself. The night this was written the gap was eight hours, because nothing
  # was watching at all.
  #
  # Five means somebody filling in a weighing on a phone waits once and it works
  # the second time. Fifteen means they give up and send a message. Either is a
  # defensible answer and this is the line to change.
  [int] $CheckEveryMinutes = 5,

  [string] $HomeDir = "C:\Users\Randy\AppData\Local\vsv-watchdog",
  [string] $RunName = "VSV cellar watchdog"
)

$ErrorActionPreference = "Stop"

if ($CheckEveryMinutes -lt 1 -or $CheckEveryMinutes -gt 1440) {
  throw "A check every $CheckEveryMinutes minutes is not an interval."
}

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$loop = Join-Path $here "watchdog-loop.ps1"
if (-not (Test-Path $loop)) { throw "watchdog-loop.ps1 is not beside this file" }

New-Item -ItemType Directory -Force -Path $HomeDir | Out-Null

# A VBScript shim, because every other way of starting PowerShell at login
# flashes a console window on the desktop once a day forever. WScript's Run with
# a window style of 0 is the one that does not.
$vbs = Join-Path $HomeDir "run-loop.vbs"
# Four quotes each side, because this string is read twice: once by
# PowerShell, which turns "" into ", and once by VBScript, where a quote
# inside a string literal has to be doubled or it ends the string. Getting
# this wrong produces a VBScript that parses as far as the path and then
# stops, and wscript sits on an error dialog nobody can see because the
# window style is hidden.
$cmd = "powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File """"$loop"""" -EveryMinutes $CheckEveryMinutes"
$vbsBody = @"
' Starts the cellar watchdog loop with no window. Generated by
' scripts\watchdog-install.ps1 in the Vitae Springs repository; edit that rather
' than this.
Set sh = CreateObject("WScript.Shell")
sh.Run "$cmd", 0, False
"@
# Written without a byte order mark on purpose. A BOM in Docker's settings file
# is what kept the cellar down for eight hours, and cscript is no happier about
# one than Docker's parser was.
[System.IO.File]::WriteAllText($vbs, $vbsBody, (New-Object System.Text.UTF8Encoding($false)))

# Stop whatever is already looping, so that changing the interval changes it
# rather than adding a second loop on the old one.
Get-CimInstance Win32_Process -Filter "Name = 'powershell.exe'" |
  Where-Object { $_.CommandLine -and $_.CommandLine -like "*watchdog-loop.ps1*" } |
  ForEach-Object {
    "stopping existing loop, pid {0}" -f $_.ProcessId
    Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue
  }

# At login, from now on.
Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" `
  -Name $RunName -Value "wscript.exe ""$vbs"""

# And right now, so installing it means it is running rather than meaning it will
# run after the next login.
Start-Process "wscript.exe" -ArgumentList """$vbs""" -WindowStyle Hidden

Start-Sleep -Seconds 6
$running = Get-CimInstance Win32_Process -Filter "Name = 'powershell.exe'" |
  Where-Object { $_.CommandLine -and $_.CommandLine -like "*watchdog-loop.ps1*" }

"installed:  {0}" -f $RunName
"interval:   every {0} minute(s)" -f $CheckEveryMinutes
"at login:   wscript.exe ""{0}""" -f $vbs
"running:    {0}" -f $(if ($running) { "yes, pid " + ($running.ProcessId -join ", ") } else { "NO, the loop did not start" })
"log:        {0}\watchdog.log" -f $HomeDir
